# Generated by Django 5.2.4 on 2025-07-24 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('boy', 'Boy'), ('girl', 'Girl'), ('any', 'Any')], max_length=10)),
                ('image', models.ImageField(upload_to='children/')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(choices=[('football', 'Football'), ('basketball', 'Basketball'), ('tennis', 'Tennis')], max_length=20)),
                ('image', models.ImageField(upload_to='programs/')),
            ],
        ),
        migrations.CreateModel(
            name='SubProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('any', 'Any')], max_length=10)),
                ('min_age', models.PositiveIntegerField()),
                ('max_age', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('description', models.TextField()),
                ('duration_weeks', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='subprograms/')),
            ],
        ),
    ]
