# Generated by Django 5.2.4 on 2025-07-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_alter_child_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subprogram',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='subprograms/'),
        ),
    ]
