# Generated by Django 5.2.4 on 2025-07-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='age_group',
        ),
        migrations.AddField(
            model_name='program',
            name='max_age',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='program',
            name='min_age',
            field=models.PositiveIntegerField(default=6),
        ),
    ]
