# Generated by Django 5.2.4 on 2025-07-23 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_program_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='gender',
            field=models.CharField(choices=[('any', 'Any'), ('male', 'Boys Only'), ('female', 'Girls Only')], default='any', max_length=10),
        ),
    ]
