# Generated by Django 5.2.4 on 2025-07-23 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_program_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subprograms', to='academy.program'),
        ),
    ]
