# Generated by Django 5.2.4 on 2025-07-23 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_program_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='duration_weeks',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
